### ISSUE TITLE
2 Fatal Exception: PickerViewModule.java

### ISSUE THREAD

**Issue by BeckZero** [beefe/react-native-picker#106]
PickerViewModule.java line 354
com.beefe.picker.PickerViewModule.hide

**Info:** 

- ReactNative: 0.39.2
- Platform: Android
- Device: HTV32
- Android OS: 6.0.1
- Rooted: false

**StackTrace:**

```
Fatal Exception: java.lang.IllegalArgumentException: View=com.android.internal.policy.PhoneWindow$DecorView{825e8d8 V.E...... R....... 0,0-1440,974} not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:424)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:350)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
       at android.app.Dialog.dismissDialog(Dialog.java:362)
       at android.app.Dialog.dismiss(Dialog.java:345)
       at com.beefe.picker.PickerViewModule.hide(PickerViewModule.java:354)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:168)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)
```

PickerViewModule.java line 334
com.beefe.picker.PickerViewModule._init

**Info:** 

- ReactNative: 0.39.2
- Platform: Android
- Device: AIRIS TM5QWM
- Android OS: 4.4.2
- Rooted: true

**StackTrace:**

```
Fatal Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@41fbca50 is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:640)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:261)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
       at android.app.Dialog.show(Dialog.java:286)
       at com.beefe.picker.PickerViewModule._init(PickerViewModule.java:334)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:193)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by stefonmarcel** [comment]
@BeckZero 
Hello I was wondering if you've figured out how to get the react-native-picker to pop up or enabled with IOS or andriod? Could you email me please marcelstefon@gmail.com

thank you

**Comment by shexiaoheng** [comment]
`react-native-picker` version ?

**Comment by stefonmarcel** [comment]
I believe it's the masters version #26 or #32 I saw

Could you provide code for a basic selection pick?

**Comment by shexiaoheng** [comment]
@stefonmarcel like [this](https://github.com/shexiaoheng/react-native-wheel) ?

**Comment by BeckZero** [comment]
Yes latest(master)

**Comment by shexiaoheng** [comment]
@BeckZero `react-native-picker` version is v4.0.14?

**Comment by BeckZero** [comment]
v4.0.11

**Comment by shexiaoheng** [comment]
@BeckZero `v4.0.12` fixed this problem
