### ISSUE TITLE
Unable to add window -- token null is not valid

### ISSUE THREAD

**Issue by lilongWang** [beefe/react-native-picker#124]
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:585)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:282)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:90)
	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1167)
	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:980)
	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:944)
	at com.beefe.picker.PickerViewModule._init(PickerViewModule.java:389)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
	at android.os.Looper.loop(Looper.java:135)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
	at java.lang.Thread.run(Thread.java:818)

**Comment by minggangLu** [comment]
I faced the same error
