### ISSUE TITLE
用你这个插件App总崩掉

### ISSUE THREAD

**Issue by xuchao321** [beefe/react-native-picker#247]
地区三级联动  一直滑动  双手速滑  就会崩掉 求解决 大bug

**Comment by RogenSH** [comment]
java.lang.IndexOutOfBoundsException: Invalid index 14, size is 9 at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:260) at java.util.ArrayList.get(ArrayList.java:313) at com.android.picker.view.PickerViewLinkage$3.onItemSelected(PickerViewLinkage.java:285) at com.android.picker.view.OnItemSelectedRunnable.run(OnItemSelectedRunnable.java:13) at android.os.Handler.handleCallback(Handler.java:815) at android.os.Handler.dispatchMessage(Handler.java:104) 
at android.os.Looper.loop(Looper.java:194) at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) at java.lang.Thread.run(Thread.java:818)

我这边的表现为ANR。不知道是不是类似的错误？

**Comment by Lxxyx** [comment]
是的，类似错误 @RogenSH 你这儿有解决吗
