### ISSUE TITLE
miui9 的机器出现弹不出弹框，并闪退。 机型包括红米note4X MI NOTE 2 MI MAX 2

### ISSUE THREAD

**Issue by zengyimou** [beefe/react-native-picker#302]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.app.Dialog.getWindow()' on a null object reference
       at com.beefe.picker.PickerViewModule._init(PickerViewModule.java:359)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:166)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:163)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
       at java.lang.Thread.run(Thread.java:760)

**Comment by zengyimou** [comment]
PickerViewModule.java:359  代码为  Window window = dialog.getWindow();

**Comment by ComeRN** [comment]
坚持修复了好几个bug，最后还是放弃了。建议使用 iberHK/react-native-picker，效果稍逊，流畅不逊。纯js实现 可维护性强了好几个档次。

**Comment by zengyimou** [comment]
@ComeRN  之后会考虑下。thx
