### ISSUE TITLE
Android Monkey Test Crash

### ISSUE THREAD

**Issue by januslo** [beefe/react-native-picker#360]
Plz see the crash log following:
// CRASH: ******* (pid 14245)

// Short Msg: java.lang.ArrayIndexOutOfBoundsException

// Long Msg: java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1

// Build Label: Xiaomi/ido/ido:5.1.1/LMY47V/8.4.26:user/release-keys

// Build Changelist: 8.4.26

// Build Time: 1524739947000

// java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1

// 	at com.facebook.react.bridge.ReadableNativeArray.getMap(ReadableNativeArray.java:154)

// 	at com.facebook.react.bridge.ReadableNativeArray.getMap(ReadableNativeArray.java:22)

// 	at com.beefe.picker.view.PickerViewLinkage$2.onItemSelected(PickerViewLinkage.java:262)

// 	at com.beefe.picker.view.OnItemSelectedRunnable.run(OnItemSelectedRunnable.java:13)

// 	at android.os.Handler.handleCallback(Handler.java:739)

// 	at android.os.Handler.dispatchMessage(Handler.java:95)

// 	at android.os.Looper.loop(Looper.java:135)

// 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)

// 	at java.lang.Thread.run(Thread.java:818)

**Comment by januslo** [comment]
请给一下建议可以找到错误位置或者直接提供一下解决方法，版本是4.3.7，RN版本0.57.1
